# Generated by Django 4.0.7 on 2022-08-14 08:42

import cartdrop.accounts.fields
import cartdrop.accounts.validators
import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_cartdropuser_email_alter_cartdropuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdropuser',
            name='email',
            field=cartdrop.accounts.fields.LowerCaseEmailField(error_messages={'unique': 'A user with this email already exist'}, max_length=50, unique=True, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='cartdropuser',
            name='first_name',
            field=models.CharField(blank=True, db_index=True, max_length=25, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='cartdropuser',
            name='number',
            field=models.CharField(blank=True, error_messages={'unique': 'This number is already registered with us please try logging in'}, max_length=10, null=True, unique=True, validators=[cartdrop.accounts.validators.number_validator], verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='cartdropuser',
            name='username',
            field=cartdrop.accounts.fields.LowerCaseCharField(error_messages={'unique': 'A user with that username already exist'}, help_text='Required. 50 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=50, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Username'),
        ),
    ]
